---
- name: Initialize Docker Swarm on manager
  hosts: managers
  become: true

  tasks:
    - name: Initialize Swarm
      shell: docker swarm init --advertise-addr 192.168.56.10
      register: swarm_init
      failed_when:
        - swarm_init.rc != 0
        - "'already part of a swarm' not in swarm_init.stderr"
      changed_when: swarm_init.rc == 0

    - name: Get worker join token
      shell: docker swarm join-token worker -q
      register: worker_token
      changed_when: false

    - name: Save worker token
      set_fact:
        swarm_worker_token: "{{ worker_token.stdout }}"

- name: Join workers to Swarm
  hosts: workers
  become: true

  tasks:
    - name: Join Swarm as worker
      shell: >
        docker swarm join
        --token {{ hostvars['manager']['swarm_worker_token'] }}
        192.168.56.10:2377
      register: swarm_join
      failed_when:
        - swarm_join.rc != 0
        - "'already part of a swarm' not in swarm_join.stderr"
      changed_when: swarm_join.rc == 0
