Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  {
    "manager"   => { ip: "192.168.56.10", cpus: 1, memory: 2048 },
    "worker-01" => { ip: "192.168.56.11", cpus: 1, memory: 1024 },
    "worker-02" => { ip: "192.168.56.12", cpus: 1, memory: 1024 },
  }.each do |name, cfg|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: cfg[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.name   = name
        vb.cpus   = cfg[:cpus]
        vb.memory = cfg[:memory]
      end
    end
  end
end
